#!/usr/bin/env python3
"""Clone task bundles and append audited custom-formula hints."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path


FLAG_CLASSES = {"custom_logic", "literal_embedded"}
EXPECTED_MODEL = "gpt-5.6-terra-high"
OUTPUT_HEADING = "\n## Output\n"
NUMBER_RE = re.compile(
    r"(?<![A-Za-z0-9_])[-+]?(?:\d+(?:,\d{3})*(?:\.\d+)?|\.\d+)"
    r"(?:[eE][-+]?\d+)?"
)


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def flagged_bands(report: dict) -> set[str]:
    return {
        str(series["band"])
        for series in report.get("series", [])
        if series.get("class") in FLAG_CLASSES
    }


def render_section(spec: dict) -> str:
    hints = spec.get("hints") or []
    if not hints:
        return ""
    lines = [
        "## Custom formula hints",
        "",
        "These are method assumptions needed to reconstruct non-standard formulas in",
        "this workbook. They describe calculation logic, not the requested answers.",
        "",
    ]
    for hint in hints:
        bands = ", ".join("`%s`" % band for band in hint["bands"])
        lines.append("- **%s** (%s): %s" % (
            hint["title"].strip(), bands, hint["guidance"].strip()))
    return "\n".join(lines) + "\n\n"


def numeric_targets(bundle: Path) -> list[float]:
    key = json.loads((bundle / "tests" / "answer_key.json").read_text())
    return [
        float(value)
        for value in (key.get("targets") or {}).values()
        if isinstance(value, (int, float)) and not isinstance(value, bool)
    ]


def audit_no_answers(spec: dict, targets: list[float]):
    """Fail if a numeric hint literal exactly reproduces a target answer."""
    collisions = []
    for hint in spec.get("hints") or []:
        for raw in NUMBER_RE.findall(hint.get("guidance", "")):
            try:
                value = float(raw.replace(",", ""))
            except ValueError:
                continue
            for target in targets:
                # Trivial round outputs (especially zero checks) collide with
                # ordinary method language by accident, not by answer leakage.
                if float(target).is_integer() and abs(target) < 10000:
                    continue
                if abs(value - target) <= 1e-12 * max(1.0, abs(target)):
                    collisions.append((hint.get("title"), raw, target))
    if collisions:
        raise ValueError("hint contains target answer value(s): %r" % collisions)


def validate_spec(task: str, spec: dict, report: dict):
    if report.get("schema_version") != "2.0":
        raise ValueError("%s: formula report schema must be 2.0" % task)
    if (report.get("generator") or {}).get("model") != EXPECTED_MODEL:
        raise ValueError("%s: formula report was not generated by %s"
                         % (task, EXPECTED_MODEL))
    if report.get("verdict") == "REVIEW":
        raise ValueError("%s: unclassified formula variables require review" % task)
    if report.get("task") != task:
        raise ValueError("%s: report task field is %r"
                         % (task, report.get("task")))
    if spec.get("schema_version") != "1.0":
        raise ValueError("%s: hint schema must be 1.0" % task)
    if spec.get("task") != task:
        raise ValueError("%s: hint task field is %r" % (task, spec.get("task")))
    seen = []
    for index, hint in enumerate(spec.get("hints") or []):
        for key in ("title", "guidance", "bands", "classes"):
            if not hint.get(key):
                raise ValueError("%s hint %d: missing %s" % (task, index, key))
        if "=" in hint["guidance"]:
            raise ValueError("%s hint %d: guidance contains a formula" % (task, index))
        if not set(hint["classes"]).issubset(FLAG_CLASSES):
            raise ValueError("%s hint %d: excluded class included" % (task, index))
        seen.extend(hint["bands"])
    expected = flagged_bands(report)
    actual = set(seen)
    duplicates = sorted({band for band in seen if seen.count(band) > 1})
    if actual != expected or duplicates:
        raise ValueError(
            "%s: hint coverage mismatch; missing=%r extra=%r duplicates=%r"
            % (task, sorted(expected - actual), sorted(actual - expected), duplicates)
        )


def load_formula_artifacts(task: str, report_path: Path, hints_path: Path,
                           targets: list[float], context_path: Path | None = None):
    if context_path is not None:
        validator = (
            Path(__file__).resolve().parent
            / ".cursor" / "skills" / "custom-formula-gate"
            / "scripts" / "validate_gate_outputs.py"
        )
        subprocess.run(
            [
                sys.executable,
                str(validator),
                str(context_path),
                str(report_path),
                str(hints_path),
            ],
            check=True,
        )
    report = json.loads(report_path.read_text(encoding="utf-8"))
    spec = json.loads(hints_path.read_text(encoding="utf-8"))
    validate_spec(task, spec, report)
    audit_no_answers(spec, targets)
    return report, spec


def clone_task(source: Path, destination: Path, spec: dict):
    if destination.exists():
        shutil.rmtree(destination)
    shutil.copytree(source, destination)

    instruction_path = destination / "instruction.md"
    instruction = instruction_path.read_text(encoding="utf-8")
    section = render_section(spec)
    if section:
        if OUTPUT_HEADING not in instruction:
            raise ValueError("%s has no Output heading" % source.name)
        instruction = instruction.replace(
            OUTPUT_HEADING, "\n" + section + "## Output\n", 1
        )
        instruction_path.write_text(instruction, encoding="utf-8")

    hint_path = destination / "tests" / "formula_hints.json"
    hint_path.write_text(json.dumps(spec, indent=2) + "\n", encoding="utf-8")


def verify_clone(source: Path, destination: Path):
    excluded = {"instruction.md", "tests/formula_hints.json"}
    source_files = {
        str(path.relative_to(source)): path
        for path in source.rglob("*") if path.is_file()
    }
    destination_files = {
        str(path.relative_to(destination)): path
        for path in destination.rglob("*") if path.is_file()
    }
    expected_paths = set(source_files) | {"tests/formula_hints.json"}
    if set(destination_files) != expected_paths:
        raise ValueError("%s: cloned file set differs" % source.name)
    for relative, path in source_files.items():
        if relative not in excluded and digest(path) != digest(destination_files[relative]):
            raise ValueError("%s: %s changed unexpectedly" % (source.name, relative))


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", default="tasks_outputs")
    parser.add_argument("--hints-root", default="runs/custom-formula-gate")
    parser.add_argument("-o", "--out", default="tasks_outputs_hinted")
    args = parser.parse_args(argv)

    source_root = Path(args.source)
    hints_root = Path(args.hints_root)
    out_root = Path(args.out)
    tasks = sorted(source_root.glob("*-outputs"))
    if not tasks:
        sys.exit("no task bundles under %s" % source_root)
    out_root.mkdir(parents=True, exist_ok=True)

    total_hints = 0
    for source in tasks:
        task = source.name
        report, spec = load_formula_artifacts(
            task,
            hints_root / ("%s-report.json" % task),
            hints_root / ("%s-hints.json" % task),
            numeric_targets(source),
        )
        destination = out_root / task
        clone_task(source, destination, spec)
        verify_clone(source, destination)
        count = len(spec.get("hints") or [])
        total_hints += count
        print("%s: %d hint group(s)" % (task, count))

    stale = [
        path for path in out_root.glob("*-outputs")
        if path.name not in {task.name for task in tasks}
    ]
    if stale:
        sys.exit("stale hinted bundles remain: %s" % ", ".join(map(str, stale)))
    print("%d task(s), %d hint group(s) -> %s" % (
        len(tasks), total_hints, out_root))


if __name__ == "__main__":
    main()
